name: Deribit Signal Fetcher

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  fetch-signals:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with PAT
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests

      - name: Run Deribit fetch script
        run: python get_signals.py

      - name: Commit & Push signals.csv
        run: |
          git config user.name "DeltaBot"
          git config user.email "bot@example.com"
          git add signals.csv
          git commit -m "Auto-update from Deribit" || echo "No changes to commit"
          git push
